TaskRLite/Controllers/AuthController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Security.Claims;
using TaskRLite.Data;
using TaskRLite.Services;
using TaskRLite.Views.Auth;
namespace TaskRLite.Controllers;

public class AuthController : Controller
{
    private readonly AccountService _accountService;

    public AuthController(AccountService accountService)
    {
        _accountService = accountService;
    }

    [HttpGet]
    public IActionResult Register()
    {
        return View();
    }

    [HttpGet]
    public IActionResult Login()
    {
        return View();
    }

    [HttpGet]
    public IActionResult Logout()
    {
        HttpContext.SignOutAsync();

        return RedirectToAction(nameof(HomeController.Index), HomeController.Name);
    }


    [HttpPost]
    public async Task<IActionResult> Register(TaskRLite.Views.Auth.RegisterVm form)
    {
        if (ModelState.IsValid)
        {
            bool success = await _accountService.RegisterNewUserAsync(form.Username, form.Password, form.Email);
            if (!success)
            {
                TempData["ErrorMessage"] = "Registration failed";
                // Todo testln?
                return RedirectToAction(nameof(Register));
                return View();
            }
            Console.WriteLine($"Jemand hat sich mit {form.Username} und {form.Password} registriert");
            return RedirectToAction(nameof(Login));
        }
        else
        {
            return View();
        }
    }

    [HttpPost]
    public async Task<IActionResult> Login(string email, string password)
    {
        var userCanLogIn = await _accountService.CanUserLogInAsync(email, password);
        Console.WriteLine($"Jemand hat sich mit {email} und {password} eingeloggt: {userCanLogIn}");

        if (userCanLogIn)
        {
            //Wir erkennen den Benutzer, und er darf sich wirklich "einloggen"
            var role = await LogUserIntoWebApp(email);
            if (role.RoleName == "Admin")
            {
                return RedirectToAction(nameof(AdminController.UserOverView), AdminController.Name);
            }
            // Free- und Premium-Tier Benutzer sollen auf die Übersichtsseite ihrer To - Do Listen weitergeleitet werden,
            return RedirectToAction(nameof(ToDoController.Index), ToDoController.Name);
        }
        else //Wenn wir den Benutzer NICHT erkennen, ...
        {
            //...wird er auf die Login-Seite zurückgeleitet
            TempData["ErrorMessage"] = "Zugangsdaten Falsch";            
            return RedirectToAction(nameof(Login));
        }
    }

    [NonAction]
    private async Task<AppUserRole> LogUserIntoWebApp(string email)
    {
        //1. Claims (Behauptungen) über den Benutzer zusammentragen
        //Ein Claim ist einfach nur ein Key-Value-Pair - Ein Wert mit einem bestimmten Namen
        var claim = new Claim("LastLogin", DateTime.Now.ToString());

        AppUser user = await _accountService.GetUserByEmail(email);

        //Damit das ASP.NET Core Auth-System mit Cookies funktioniert, ist ein Claim besonders wichtig: Der Name-Claim
        var nameClaim = new Claim(ClaimTypes.Name, user.Username);

        //AppRole role = await _accountService.GetRoleByUserNameAsync(email);
        //var roleClaim = new Claim(ClaimTypes.Role, role.RoleName);

        var roleClaim = new Claim(ClaimTypes.Role, user.AppRole.RoleName);

        //Alle Claims die dieser Liste (und damit der Identity bzw. dem Principal) hinzugefügt werden,
        //...werden dann im Auth-Cookie gespeichert (und können dort auch wieder ausgelesen werden)
        var claims = new List<Claim>()
        {
            claim, nameClaim,roleClaim
        };


        //2. Mit den Claims eine Identität erstellen
        //In unserem Fall benötigt der Principal eine Identität, da wir einzelne Benutzer voneinander unterscheiden wollen
        var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

        //3. Die Identität einem Rechteinhaber zuweisen
        //In der Microsoft bzw. .NET Welt ist ein "Principal" ein Rechteinhaber
        var claimsPrincipal = new ClaimsPrincipal(claimsIdentity);

        await Console.Out.WriteLineAsync(nameClaim.Value + " " + roleClaim.Value);
        //4. Den Rechteinhaber in der Anwendung "registrieren"
        //Um einen Benutzer in der Webanwendung als "eingeloggt" zu "markieren" (und ihm das Auth-Cookie zu schicken),
        //gibt es die Methode SignInAsync

        await HttpContext.SignInAsync(
            CookieAuthenticationDefaults.AuthenticationScheme,
            claimsPrincipal
            );

        await Console.Out.WriteLineAsync(nameClaim.Value + " eingeloggt");

        //Der ClaimsPrincipal der hier erzeugt und "registriert" wird, ist nachher auch über eine spezielle Variable
        //...in Controllern und Views abrufbar. Die Variable heißt "User" und enthält neben allen Informationen
        //...die über die Claims hier gespeichert werden, auch nützliche Hilfsmethoden/-Eigenschaften.

        //zB
        //User.Identity.Name erlaubt Zugriff auf den abgespeicherten Namen
        //User.Identity.IsAuthenticated meldet, ob gerade ein Benutzer eingeloggt ist oder nicht (nützlich, um zB
        //...Interface-Elemente anzuzeigen bzw. zu verstecken, je nachdem ob ein eingeloggter oder anonymer Benutzer
        //...die View gerade ansieht).
        //User.Claims erlaubt Zugriff auf alle gespeicherten Claims
        return user.AppRole;
    }
}

TaskRLite/Controllers/TagsController.cs
using Azure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Drawing;
using TaskRLite.Data;
using TaskRLite.Models;
using TaskRLite.Services;

namespace TaskRLite.Controllers
{
    [Authorize(Roles = "Admin, FreeUser, PremiumUser")]
    public class TagsController : Controller
    {

        public static string Name = nameof(TagsController).Replace("Controller", null);
        private readonly ToDoListService _toDoListService;
        private readonly AccountService _accountService;

        public TagsController(ToDoListService toDoListService, AccountService accountService)
        {
            _toDoListService = toDoListService;
            _accountService = accountService;
        }

        public async Task<IActionResult> Index()
        {
            var userId = await _accountService.GetAppUserIdByNameAsync(this.User.Identity.Name);
            List<Data.Tag> tags = new();
            if (User.IsInRole("Admin"))
            {
                tags = await _toDoListService.GetGlobalTagsAsync();
            }
            else
            {
                tags = await _toDoListService.GetUserTagsAsync(userId);
            }
            TagIndexVm vm = new TagIndexVm()
            {
                Tags = tags.ToDictionary(o => o.Id),
            };
            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> CreateTag(TagIndexVm vm)
        {
            if (ModelState.IsValid)
            {
                var tag = new Tag
                {
                    HexColor = vm.HexColor.Replace("#", ""),
                    Name = vm.Name
                };

                #region Tags Limit
                if (!User.IsInRole("Admin"))
                {
                    int userid = await _accountService.GetAppUserIdByNameAsync(this.User.Identity.Name);
                    tag.AppUserId = userid;
                    var userTags = await _toDoListService.GetUserTagsAsync(userid);
                    if (userTags.Count >= 20)
                    {
                        TempData["ErrorMessage"] = "Maximum 20 Tags!";
                        return RedirectToAction(nameof(Index));
                    }
                    else if (userTags.Where(o => o.Name == vm.Name).FirstOrDefault() != null)
                    {
                        TempData["ErrorMessage"] = "Tag mit gleichem Namen existiert bereits!";
                        return RedirectToAction(nameof(Index));
                    }
                }
                else
                {
                    var globalTags = await _toDoListService.GetGlobalTagsAsync();
                    if (globalTags.Count >= 20)
                    {
                        TempData["ErrorMessage"] = "Maximum 20 Tags!";
                        return RedirectToAction(nameof(Index));
                    }
                    else if (globalTags.Where(o => o.Name == vm.Name).FirstOrDefault() != null)
                    {
                        TempData["ErrorMessage"] = "Tag mit gleichem Namen existiert bereits!";
                        return RedirectToAction(nameof(Index));
                    }
                }
                #endregion

                int result;
                if (vm.Id == null)
                {
                    await Console.Out.WriteLineAsync("newtag" + vm.Id + " " + vm.Name + " " + vm.HexColor);
                    result = await _toDoListService.CreateTagAsync(tag);
                }
                else
                {
                    await Console.Out.WriteLineAsync("Id:" + vm.Id + " " + vm.Name + " " + vm.HexColor);
                    tag.Id = (int)vm.Id;
                    result = await _toDoListService.UpdateTagAsync(tag);
                }
                if (result == -1)
                {
                    TempData["ErrorMessage"] = "gehtned";
                }
                else if (result == 1)
                {
                    TempData["SuccessMessage"] = "Eintrag geUpdated";
                }
                else if (result == 0)
                {
                    TempData["ErrorMessage"] = "keine änderungen";
                }
                else
                {
                    TempData["ErrorMessage"] = "gehtned";
                }
                return RedirectToAction(nameof(Index));
            }
            else
            {
                var errormessages = ModelState.Values.SelectMany(v => v.Errors.Select(b => b.ErrorMessage));
                var errorstring = string.Join("\n ", errormessages);
                TempData["ErrorMessage"] = errorstring;
                return RedirectToAction(nameof(Index));
            }


        }

        public async Task<IActionResult> DeleteTag(int id)
        {
            int result = await _toDoListService.TryDeleteTagByIdAsync(id);
            if (result == -1)
            {
                TempData["ErrorMessage"] = "Vorgang fehlgeschlagen";
            }
            if (result == -2)
            {
                TempData["ErrorMessage"] = "Verwendete Tags können nicht gelöscht werden";
            }
            if (result >= 1)
            {
                TempData["SuccessMessage"] = "Eintrag gelöscht";
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

TaskRLite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskR</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TaskRLite.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TaskR</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="UserOverView">Users</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="ToDo" asp-action="Index">ToDos</a>
                                </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Tags" asp-action="Index">Tags</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Register">Register</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TaskR - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>